apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-stable
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-stable
spec:
  selector:
    matchLabels:
      app: python-stable
  replicas: 1
  template:
    metadata:
      labels:
        app: python-stable
    spec:
      containers:
      - name: python-stable
        image:python-stable
      